### ISSUE TITLE
Model.dataFormat in Internet Explorer issue

### ISSUE THREAD

**Issue by martienvlent** [NorthwoodsSoftware/GoJS#9] opened 2015-07-03 01:46 UTC
When I set Model.dataFormat  to a non-empty string, pasting in the same model is no longer possible in IE11. It works fine in Chrome. Can you think of anything I can do to solve this?

**Comment by WalterNorthwoods** [comment] 2015-07-03 21:33
I'm unable to reproduce this problem.  I had a page with three Diagrams.  Diagrams A and B had their respective model's **Model.dataFormat** at the default value, the empty string; Diagram C's **Model.dataFormat** was set to "THREE".  I could easily copy and paste from A to A and from A to B, but I could not from A to C.  This is the expected behavior, and it worked the same way in IE, Firefox, and Chrome.

**Comment by simonsarris** [comment] 2015-07-06 20:22
Closing this issue. If you believe you've found a bug please re-open an issue with a reproducible case, or contact us directly: http://www.nwoods.com/contact.html

If you need support, please use the forum: http://forum.nwoods.com/?FID=8

**Closed by simonsarris** 2015-07-06 20:22 UTC

**Comment by martienvlent** [comment] 2015-07-06 21:31
You were right. The problem was elsewhere in my code.
Sorry for the inconvenience.
