### ISSUE TITLE
addNodeAndLink function crashing

### ISSUE THREAD

**Issue by hmorkonda** [NorthwoodsSoftware/GoJS#147] opened 2021-07-06 05:43 UTC
https://gojs.net/latest/intro/selection.html#MoreComplexAdornments

I am trying to copy paste and run the exact same code in the browser. However, the program crashes when adding node to child of a child. I have also used online compilers to test and run. Please clarify. 

Here's a link to my full code: https://replit.com/@HarineeMorko/WhoppingWiltedFactorial#index.html

**Comment by WalterNorthwoods** [comment] 2021-07-06 11:52
We'll investigate.  Thanks for reporting the problem.

**Comment by WalterNorthwoods** [comment] 2021-07-06 15:46
The browser didn't "crash", did it?  Do you mean that the browser seemed to "hang"?

I think the problem is that the link route computation happen to run into a case that feels like an infinite loop, although in reality it was just extremely slow because the iterations were huge.  And I think that case, which took me a while to reproduce reliably, was due to tiny floating point errors which we were not accounting for.

Anyway, soon that will be fixed in the next release, 2.1.45.  Thank you again for reporting the issue.

**Closed by WalterNorthwoods** 2021-07-06 15:46 UTC
