### ISSUE TITLE
The drawing will be shifted to the right instead of at the specified position. What is the situation

### ISSUE THREAD

**Issue by A-lie** [NorthwoodsSoftware/GoJS#109] opened 2020-09-01 03:08 UTC
The first drag out is not at the specified position, but will offset to the right. You need to drag again

**Comment by WalterNorthwoods** [comment] 2020-09-01 10:53
I am closing this because you do not appear to be reporting a bug nor do you provide a minimal reproducible example demonstrating the problem that you have nor even some screenshots.  Ask about your problem in the forum.

**Closed by WalterNorthwoods** 2020-09-01 10:53 UTC

**Comment by A-lie** [comment] 2020-09-02 00:36
![~SHP4$(FOKQ$C79Z4RR21KU](https://user-images.githubusercontent.com/55788805/91919019-35af9c80-ecf7-11ea-9ff5-a563f2951fcb.png)

**Comment by A-lie** [comment] 2020-09-02 00:41
[addInfos.zip](https://github.com/NorthwoodsSoftware/GoJS/files/5159418/addInfos.zip)
