### ISSUE TITLE
GuidedDraggingTool error

### ISSUE THREAD

**Issue by akagaeng** [NorthwoodsSoftware/GoJS#36] opened 2017-04-12 01:22 UTC
Hi.

I found error in GuidedDraggingTool. The condition of occurring error in the sample page([hyperlink](http://gojs.net/latest/extensions/GuidedDragging.html)) is dragging links(not nodes). When I drag a link, looping errors occur. I captured one of them.
![image](https://cloud.githubusercontent.com/assets/17076841/24937146/9c352f06-1f69-11e7-9ebc-79125f360958.png)

**Comment by WalterNorthwoods** [comment] 2017-04-13 14:15
Thanks for noticing this error in that sample.  The problem is that it is trying to show guidelines when nothing is being dragged.  The fix is to modify the GuidedDraggingTool.js file:
```
GuidedDraggingTool.prototype.doDragOver = function(pt, obj) {
  // clear all existing guidelines in case either show... method decides to show a guideline
  this.clearGuidelines();

  // gets the selected part
  var partItr = (this.copiedParts || this.draggedParts).iterator;
  if (partItr.next()) {
    var part = partItr.key;

    this.showHorizontalMatches(part, this.isGuidelineEnabled, false);
    this.showVerticalMatches(part, this.isGuidelineEnabled, false);
  }
}

/**
* On a mouse-up, snaps the selected part to the nearest guideline.
* If no guidelines are showing, the part remains at its position.
* This calls {@link #guidelineSnap}.
* @this {GuidedDraggingTool}
*/
GuidedDraggingTool.prototype.doDropOnto = function(pt, obj) {
  // gets the selected (perhaps copied) Part
  var partItr = (this.copiedParts || this.draggedParts).iterator;
  if (partItr.next()) {
    var part = partItr.key;

    // snaps only when the mouse is released without shift modifier
    var e = this.diagram.lastInput;
    var snap = this.isGuidelineSnapEnabled && !e.shift;

    this.showHorizontalMatches(part, this.isGuidelineEnabled, snap);
    this.showVerticalMatches(part, this.isGuidelineEnabled, snap);
  }
}
```
This will be in our next release, 1.7.8.

**Closed by WalterNorthwoods** 2017-04-13 14:15 UTC
